export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const CONFIRM_CODE_SUCCESS = " CONFIRM_CODE_SUCCESS";
export const CONFIRM_CODE_FAILURE = " CONFIRM_CODE_FAILURE";

export const CHECK_AUTHENTICATED_USER = "CHECK_AUTHENTICATED_USER";
export const CHECK_USER_FAIL = "CHECK_USER_FAIL";

export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_OUT_FAILURE = "SIGN_OUT_FAILURE";

export const FORGOT_PASSWORD_CODE = "FORGOT_PASSWORD_CODE";
export const FORGOT_PASSWORD_CODE_FAIL = "FORGOT_PASSWORD_CODE_FAIL";

export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";

export const EVENT_PENDING = "EVENT_PENDING";
