export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const  CONFIRM_CODE_SUCCESS = " CONFIRM_CODE_SUCCESS";
export const  CONFIRM_CODE_FAILURE = " CONFIRM_CODE_FAILURE";
